name: Build, Test, Analyze and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

env:
  DOTNET_VERSION: '9.0.x'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-test-analyze:
    name: Build, Test and Code Analysis
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Necessário para SonarQube

    # 2. Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # 3. Setup Java (para SonarScanner)
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 4. Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # 5. Install SonarScanner
    - name: Install SonarScanner for .NET
      run: dotnet tool install --global dotnet-sonarscanner

    # 6. Begin SonarQube analysis
    - name: Begin SonarQube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      run: |
        dotnet sonarscanner begin \
          /k:"${SONAR_PROJECT_KEY}" \
          /o:"${SONAR_ORGANIZATION}" \
          /d:sonar.host.url="${SONAR_HOST_URL:-http://localhost:9000}" \
          /d:sonar.login="${SONAR_TOKEN}" \
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" \
          /d:sonar.coverage.exclusions="**Tests.cs,**Tests/**,**/Migrations/**" \
          /d:sonar.verbose=true
    # 7. Build solution
    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    # 8. Run tests with coverage
    - name: Run tests with coverage
      run: |
        dotnet test --configuration Release --no-build \
          --collect:"XPlat Code Coverage" \
          --results-directory ./coverage \
          -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    # 9. End SonarQube analysis
    - name: End SonarQube analysis and write report-task.txt
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      shell: bash
      run: |
        set -eo pipefail
        mkdir -p .scannerwork
        echo "Running dotnet sonarscanner end and capturing output..."
        # Capture output (stdout+stderr) so we can parse CE task id
        OUTPUT_FILE=sonar_end_output.log
        if ! dotnet sonarscanner end /d:sonar.login="${SONAR_TOKEN}" 2>&1 | tee "$OUTPUT_FILE"; then
          echo "dotnet sonarscanner end failed. See $OUTPUT_FILE for details" >&2
          exit 1
        fi
        # Try to extract CE task id from the output (pattern: api/ce/task?id=...)
        # Treat the log as text even if grep detects binary data, and fall back to `strings` if needed.
        CE_ID=$(grep -a -oE 'api/ce/task\?id=[A-Za-z0-9_-]+' "$OUTPUT_FILE" | head -n1 | sed 's/.*id=//') || true
        if [ -z "$CE_ID" ]; then
          # Fallback: filter printable strings then grep (if `strings` is available)
          if command -v strings >/dev/null 2>&1; then
            CE_ID=$(strings "$OUTPUT_FILE" | grep -oE 'api/ce/task\?id=[A-Za-z0-9_-]+' | head -n1 | sed 's/.*id=//') || true
          fi
        fi
        if [ -n "$CE_ID" ]; then
          # Normalize host URL (remove trailing slash)
          HOST="${SONAR_HOST_URL:-http://localhost:9000}"
          HOST=${HOST%/}
          echo "ceTaskUrl=${HOST}/api/ce/task?id=${CE_ID}" > .scannerwork/report-task.txt
          echo "Wrote .scannerwork/report-task.txt with CE task id: ${CE_ID}"
        else
          echo "WARNING: could not find CE task id in sonarscanner output. Showing output for debug:" >&2
          sed -n '1,200p' "$OUTPUT_FILE" >&2 || true
          echo "Failing the job because report-task.txt is required for the Quality Gate action." >&2
          exit 1
        fi
    # 10. Wait for Quality Gate result
    # 10. Diagnostic: query SonarCloud for CE task and Quality Gate details (helps debug failures)
    - name: Debug SonarCloud Quality Gate
      shell: bash
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      run: |
        set -euo pipefail
        echo "Reading .scannerwork/report-task.txt"
        if [ -f .scannerwork/report-task.txt ]; then
          cat .scannerwork/report-task.txt || true
        else
          echo "WARN: .scannerwork/report-task.txt not found"
        fi
        # Try to extract CE id (if present) and show CE task JSON
        CE_URL=$(grep -a -oE 'https?://[^ ]+/api/ce/task\?id=[A-Za-z0-9_-]+' .scannerwork/report-task.txt 2>/dev/null || true)
        if [ -n "${CE_URL}" ]; then
          echo "Found CE URL: ${CE_URL}"
          echo "Fetching CE task JSON..."
          curl -s -u "${SONAR_TOKEN}:" "${CE_URL}" | python -m json.tool || curl -s -u "${SONAR_TOKEN}:" "${CE_URL}" || true
        else
          echo "No CE URL found in report-task.txt; will attempt project_status API"
        fi
        echo "Fetching project quality gate status for project: ${SONAR_PROJECT_KEY}"
        curl -s -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL%/}/api/qualitygates/project_status?projectKey=${SONAR_PROJECT_KEY}" | python -m json.tool || curl -s -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL%/}/api/qualitygates/project_status?projectKey=${SONAR_PROJECT_KEY}" || true
    # 11. Wait for Quality Gate result
    - name: Wait for Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build-and-push-docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: build-test-analyze
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    strategy:
      matrix:
        service:
          - name: cadastro-api
            dockerfile: src/Services/Cadastro/EmployeeManagement.Cadastro.API/Dockerfile
            context: .
          - name: ativacao-worker
            dockerfile: src/Services/Ativacao/EmployeeManagement.Ativacao.Worker/Dockerfile
            context: .
          - name: notificacoes-api
            dockerfile: src/Services/Notificacoes/EmployeeManagement.Notificacoes.API/Dockerfile
            context: .

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service.name }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Build and push Docker image - ${{ matrix.service.name }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.service.context }}
        file: ${{ matrix.service.dockerfile }}
        push: ${{ github.event_name == 'push' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build-test-analyze

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      with:
        sarif_file: 'trivy-results.sarif'